Add testing to workflow

diff --git a/.github/workflows/deploy-gen-lambda.yaml b/.github/workflows/deploy-gen-lambda.yaml
--- a/.github/workflows/deploy-gen-lambda.yaml
+++ b/.github/workflows/deploy-gen-lambda.yaml
@@ -34,3 +34,45 @@ jobs:
     - name: Update Lambda function code
       run: |
         aws lambda update-function-code --function-name generateTicket --zip-file fileb://function.zip
+
+    - name: Test Lambda function
+      run: |
+        # Save the payload to a file
+        cat <<EOF > payload.json
+        {
+          "customer_name": "Alice Johnson",
+          "events": [
+            {
+              "event_id": "EVENT001",
+              "tickets": [
+                {
+                  "ticket_id": "TICKET001",
+                  "price": 50.0
+                },
+                {
+                  "ticket_id": "TICKET002",
+                  "price": 75.0
+                }
+              ]
+            },
+            {
+              "tickets": [
+                {
+                  "ticket_id": "TICKET003",
+                  "price": 100.0
+                }
+              ]
+            }
+          ]
+        }
+        EOF
+
+        # Invoke the Lambda function using its function URL (or using the function name)
+        aws lambda invoke --function-name ${{ vars.LAMBDA_URL}} --payload file://payload.json response.json
+
+        status=$(jq -r '.statusCode' response.json)
+        echo "Lambda response statusCode: $status"
+        if [ "$status" != "200" ]; then
+          echo "Error: statusCode is not 200"
+          exit 1
+        fi
